#!/bin/bash

# Demo script for Industry Starter Templates
# Shows how templates pre-fill defaults and streamline the questionnaire

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║     TDD Builder - Industry Starter Templates Demo           ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This demo shows how industry templates accelerate TDD creation"
echo "by pre-filling defaults and focusing on relevant questions."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Colors
CYAN='\033[36m'
YELLOW='\033[33m'
GREEN='\033[32m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

echo "Command:"
echo "  $ node cli.js --template saas"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Simulate template loading
echo -e "${CYAN}${BOLD}📋 Loading SaaS Starter Template${RESET}"
echo -e "${DIM}   Pre-configured template for SaaS applications with multi-tenancy,${RESET}"
echo -e "${DIM}   rate limiting, subscription billing, and SSO${RESET}"
echo -e "${DIM}   Pre-filling 35 default values${RESET}"
echo ""
echo -e "${GREEN}✓ Pre-filled 35 answers${RESET}"
echo -e "${DIM}  Tag focus: architecture, security, operations, business${RESET}"
echo -e "${DIM}  Complexity: standard${RESET}"
echo ""

# Show what's pre-filled
echo -e "${CYAN}${BOLD}Default Values Applied:${RESET}"
echo ""
echo -e "${GREEN}Architecture & Deployment:${RESET}"
echo "  ✓ deployment.model = cloud"
echo "  ✓ cloud.provider = aws"
echo "  ✓ architecture.style = microservices"
echo "  ✓ architecture.tenancy = multi-tenant"
echo "  ✓ architecture.scale = medium"
echo ""
echo -e "${GREEN}Security & Authentication:${RESET}"
echo "  ✓ security.auth = [oauth2, saml, mfa]"
echo "  ✓ security.controls = [encryption-at-rest, encryption-in-transit, ...]"
echo "  ✓ sso.providers = [google, microsoft, okta]"
echo "  ✓ sso.protocol = saml2"
echo ""
echo -e "${GREEN}Privacy & Compliance:${RESET}"
echo "  ✓ privacy.pii = true"
echo "  ✓ privacy.regulations = [gdpr, ccpa]"
echo "  ✓ privacy.controls = [data-masking, consent-management, ...]"
echo ""
echo -e "${GREEN}Business & Billing:${RESET}"
echo "  ✓ billing.model = subscription"
echo "  ✓ billing.tiers = [free, basic, premium, enterprise]"
echo "  ✓ billing.payment_provider = stripe"
echo "  ✓ api.rate_limiting = true"
echo ""
echo -e "${GREEN}Operations:${RESET}"
echo "  ✓ operations.monitoring = [metrics, logging, tracing, alerting, apm]"
echo "  ✓ operations.sla = 99.9"
echo "  ✓ database.type = postgresql"
echo "  ✓ cache.enabled = true"
echo ""
echo -e "${DIM}...and 15 more defaults${RESET}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${CYAN}${BOLD}Questionnaire Flow:${RESET}"
echo ""

# Show reduced question flow
echo -e "${BOLD}Without Template:${RESET} 15+ questions covering all aspects"
echo -e "${BOLD}With Template:${RESET}    5-7 questions (project-specific only)"
echo ""
echo "You'll only be asked:"
echo "  1. Project name"
echo "  2. Project description"
echo "  3. Problem statement"
echo "  4. Solution approach"
echo "  5. Stakeholders"
echo ""
echo -e "${DIM}Industry-standard defaults are already configured!${RESET}"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo -e "${CYAN}${BOLD}Available Templates:${RESET}"
echo ""
echo -e "${GREEN}saas${RESET}        (35 defaults) - Multi-tenancy, rate limiting, SSO"
echo -e "${GREEN}fintech${RESET}     (43 defaults) - SOC 2/PCI, audit logging, segregation of duties"
echo -e "${GREEN}ecommerce${RESET}   (57 defaults) - Catalog, inventory, checkout, payments, fraud"
echo -e "${GREEN}healthcare${RESET}  (57 defaults) - PHI/PII, HIPAA, data retention policies"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo -e "${CYAN}${BOLD}Benefits:${RESET}"
echo ""
echo "  ✓ 50-70% faster TDD creation"
echo "  ✓ Industry best practices built-in"
echo "  ✓ Compliance requirements pre-configured"
echo "  ✓ Focus on your unique requirements"
echo "  ✓ All defaults can be overridden"
echo "  ✓ Skip irrelevant questions automatically"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Try it yourself:"
echo ""
echo "  # Start with a template"
echo "  $ node cli.js --template saas"
echo "  $ node cli.js --template fintech"
echo "  $ node cli.js --template ecommerce"
echo "  $ node cli.js --template healthcare"
echo ""
echo "  # Combine with other options"
echo "  $ node cli.js --template saas --pdf"
echo "  $ node cli.js --template fintech --complexity comprehensive"
echo ""
echo "For more information:"
echo "  - templates/industries/README.md"
echo "  - INDUSTRY_TEMPLATES_SUMMARY.md"
echo ""

