name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script, skipping."
          fi

      - name: Run unit & integration tests
        run: npm test --silent

      - name: Build all targets
        run: npm run build:all

      - name: Validate Micro Builds Guide present
        run: npm run validate:microbuild

      - name: Validate no orphan template variables
        run: npm run validate:variables

      - name: Upload exports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tdd-exports
          path: |
            exports/**
            output/**
          if-no-files-found: warn