name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  SCHEMA_DRIVEN_ONBOARDING: false
  EXPORT_PATH: ./exports

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema_mode: [false, true]
    env:
      SCHEMA_DRIVEN_ONBOARDING: ${{ matrix.schema_mode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build

      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script, skipping."
          fi

      - name: Run Jest tests with coverage
        run: npm run test:jest -- --coverage --ci

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage for src/lib..."
          npm run test:jest -- --coverage --collectCoverageFrom='src/lib/**/*.ts' --coverageThreshold='{"global":{"branches":80,"functions":80,"lines":80,"statements":80}}' --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Comment coverage on PR
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: github.event_name == 'pull_request' && matrix.schema_mode == false
        continue-on-error: true
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true

      - name: Run unit & integration tests
        run: npm test --silent

      - name: Build all targets
        run: npm run build:all

      - name: Validate Micro Builds Guide present
        run: npm run validate:microbuild

      - name: Validate no orphan template variables
        run: npm run validate:variables

      - name: Test CLI with --legacy flag
        if: matrix.schema_mode == false
        run: node cli.js --legacy --noninteractive tests/sample_mcp.json
      
      - name: Test CLI in current mode
        run: node cli.js --noninteractive tests/sample_mcp.json

      - name: Upload exports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tdd-exports
          path: |
            exports/**
            output/**
          if-no-files-found: warn